# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-matrix-extended
  description: GitHub Action that when used together with reusable workflows makes it easier to workaround the limit of 256 jobs in a matrix
  homepage: https://cloudposse.com/accelerate
  topics: ""
