name: Test nested matrices 3
on:
#  # Uncomment when test added first time to register workflow and comment it back after workflow would be registered
#  #
#  # Added pull_request to register workflow from the PR.
#  # Read more https://stackoverflow.com/questions/63362126/github-actions-how-to-run-a-workflow-created-on-a-non-master-branch-from-the-wo
#  pull_request: {}
  workflow_dispatch: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: echo "Do setup"

  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./
        id: current
        with:
          sort-by: '[.version, .os, .arch] | join("-")'
          group-by: '.arch'
          nested-matrices-count: '3'
          matrix: |
            [
              {"version": "10", "os": "ubuntu-latest", "arch": "amd64"},
              {"version": "12", "os": "ubuntu-latest", "arch": "amd64"},
              {"version": "14", "os": "ubuntu-latest", "arch": "amd64"},
              {"version": "10", "os": "ubuntu-latest", "arch": "arm64"},
              {"version": "12", "os": "ubuntu-latest", "arch": "arm64"},
              {"version": "14", "os": "ubuntu-latest", "arch": "arm64"},
              {"version": "10", "os": "windows-latest", "arch": "amd64"},
              {"version": "12", "os": "windows-latest", "arch": "amd64"},
              {"version": "14", "os": "windows-latest", "arch": "amd64"},
              {"version": "10", "os": "windows-latest", "arch": "arm64"},
              {"version": "12", "os": "windows-latest", "arch": "arm64"},
              {"version": "14", "os": "windows-latest", "arch": "arm64"}            
            ]

    outputs:
      matrix: "${{ steps.current.outputs.matrix }}"

  assert:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: nick-fields/assert-action@v2
        with:
          actual: ${{ needs.test.outputs.matrix }}
          expected: '{"include":[{"name":"amd64","items":"{\"include\":[{\"name\":\"10-ubuntu-latest-amd64 - 14-windows-latest-amd64\",\"items\":\"{\\\"include\\\":[{\\\"version\\\":\\\"10\\\",\\\"os\\\":\\\"ubuntu-latest\\\",\\\"arch\\\":\\\"amd64\\\"},{\\\"version\\\":\\\"10\\\",\\\"os\\\":\\\"windows-latest\\\",\\\"arch\\\":\\\"amd64\\\"},{\\\"version\\\":\\\"12\\\",\\\"os\\\":\\\"ubuntu-latest\\\",\\\"arch\\\":\\\"amd64\\\"},{\\\"version\\\":\\\"12\\\",\\\"os\\\":\\\"windows-latest\\\",\\\"arch\\\":\\\"amd64\\\"},{\\\"version\\\":\\\"14\\\",\\\"os\\\":\\\"ubuntu-latest\\\",\\\"arch\\\":\\\"amd64\\\"},{\\\"version\\\":\\\"14\\\",\\\"os\\\":\\\"windows-latest\\\",\\\"arch\\\":\\\"amd64\\\"}]}\"}]}"},{"name":"arm64","items":"{\"include\":[{\"name\":\"10-ubuntu-latest-arm64 - 14-windows-latest-arm64\",\"items\":\"{\\\"include\\\":[{\\\"version\\\":\\\"10\\\",\\\"os\\\":\\\"ubuntu-latest\\\",\\\"arch\\\":\\\"arm64\\\"},{\\\"version\\\":\\\"10\\\",\\\"os\\\":\\\"windows-latest\\\",\\\"arch\\\":\\\"arm64\\\"},{\\\"version\\\":\\\"12\\\",\\\"os\\\":\\\"ubuntu-latest\\\",\\\"arch\\\":\\\"arm64\\\"},{\\\"version\\\":\\\"12\\\",\\\"os\\\":\\\"windows-latest\\\",\\\"arch\\\":\\\"arm64\\\"},{\\\"version\\\":\\\"14\\\",\\\"os\\\":\\\"ubuntu-latest\\\",\\\"arch\\\":\\\"arm64\\\"},{\\\"version\\\":\\\"14\\\",\\\"os\\\":\\\"windows-latest\\\",\\\"arch\\\":\\\"arm64\\\"}]}\"}]}"}]}'

  teardown:
    runs-on: ubuntu-latest
    needs: [assert]
    if: ${{ always() }}
    steps:
      - name: Tear down
        run: echo "Do Tear down"
